name: Hello World

#Events 

on:
  push:
    branches:
      -main

      pill_request:
      branches:
       -main

       workflow_dispatch:


       #Workflow / Jobs 

       jobs:
         hello:
           runs-on: ubuntu-lates
           steps:
           -uses: actions/checkout@v4
           -name: Hello
           run: echo "Hellow World"
           shell: bash
